name: ACCELQ Automation Action
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: ACCELQ Github-A Connect
      # You may pin to the exact commit or the version.
      # uses: accelq/accelq-ci-github-actions@276626dc384b381145d2c38db2502a86afa34cf5
      uses: accelq/accelq-ci-github-actions@v1.1
      with:
        # Your ACCELQ Application URL in the exact following format: https://<hostname>:<port_num>
        appURL: https://133bce11a49c.ngrok.io
        # Your ACCELQ User ID
        userName: "tenantAdmin@accelq.com" 
        # API key available in Profile section of ACCELQ
        apiKey: "Y60B5wN-bCZGKaY2jqNdhl2HZrvAj71cykqJGo0ONKE"
        # Tenant Code displayed in the Profile section of ACCELQ
        tenantCode: "accelq"
        # This ID should come from the CI job you saved in ACCELQ application
        jobId: "11"
        # Run Params(optional) should be of the form (Customer Name=John Todd & Customer Id=232)
        runParam: '{"User name": "qbankadmin", "Pswd": "pass123", "App URL": "qbank.accelq.com"}'
        # Proxy Host (optional)
#         proxyHost: # optional
        # Proxy Port (optional)
#         proxyPort: # optional
